### ISSUE TITLE
Poor performance (Quest 2 - Win 11)

### ISSUE THREAD

**Issue by miskeeping** [ItsKaitlyn03/OculusKiller#5] opened 2022-04-27 00:54 UTC
Unsure of why but I'm getting very poor performance, feels somewhere in the range of 30-45 fps, even just sitting around in the Steam VR menu.

I'm using a Quest 2 via the official link cable and my settings are the following:
![image](https://user-images.githubusercontent.com/26336877/165416671-dbbab06e-186c-4721-8ae2-a5cd8e05619d.png)

Unsure of how or why this is happening, nor do I have steps to reproduce as this happens every time I launch "Oculus Link" through the Quest 2's menu.

Any advice or ideas are very much appreciated!

**Comment by ItsKaitlyn03** [comment] 2022-04-27 01:42
Closing because the issue is that Windows 11 is big dumb and broken with Oculus.

**Closed by ItsKaitlyn03** 2022-04-27 01:42 UTC
